%token <stringVal> T_FUNC_ABS
%token <stringVal> T_FUNC_AND
%token <stringVal> T_FUNC_AVERAGE
%token <stringVal> T_FUNC_COUNT
%token <stringVal> T_FUNC_DEFINED
%token <stringVal> T_FUNC_FALSE
%token <stringVal> T_FUNC_INT
%token <stringVal> T_FUNC_MAX
%token <stringVal> T_FUNC_MIN
%token <stringVal> T_FUNC_MOD
%token <stringVal> T_FUNC_NOT
%token <stringVal> T_FUNC_OR
%token <stringVal> T_FUNC_PRODUCT
%token <stringVal> T_FUNC_ROUND
%token <stringVal> T_FUNC_SIGN
%token <stringVal> T_FUNC_SUM
%token <stringVal> T_FUNC_TRUE

%nonassoc T_FUNC_ABS
%nonassoc T_FUNC_AND
%nonassoc T_FUNC_AVERAGE
%nonassoc T_FUNC_COUNT
%nonassoc T_FUNC_DEFINED
%nonassoc T_FUNC_FALSE
%nonassoc T_FUNC_INT
%nonassoc T_FUNC_MAX
%nonassoc T_FUNC_MIN
%nonassoc T_FUNC_MOD
%nonassoc T_FUNC_NOT
%nonassoc T_FUNC_OR
%nonassoc T_FUNC_PRODUCT
%nonassoc T_FUNC_ROUND
%nonassoc T_FUNC_SIGN
%nonassoc T_FUNC_SUM
%nonassoc T_FUNC_TRUE

