%token<stringVal> T_FUNC_ABSREF

%token<stringVal> T_FUNC_ACTIVE_CELL

%token<stringVal> T_FUNC_ADD_BAR

%token<stringVal> T_FUNC_ADD_COMMAND

%token<stringVal> T_FUNC_ADD_MENU

%token<stringVal> T_FUNC_ADD_TOOLBAR

%token<stringVal> T_FUNC_APP_TITLE

%token<stringVal> T_FUNC_ARGUMENT

%token<stringVal> T_FUNC_BREAK

%token<stringVal> T_FUNC_CALL

%token<stringVal> T_FUNC_CALLER

%token<stringVal> T_FUNC_CANCEL_KEY

%token<stringVal> T_FUNC_CHECK_COMMAND

%token<stringVal> T_FUNC_CREATE_OBJECT

%token<stringVal> T_FUNC_CUSTOM_REPEAT

%token<stringVal> T_FUNC_CUSTOM_UNDO

%token<stringVal> T_FUNC_DELETE_BAR

%token<stringVal> T_FUNC_DELETE_COMMAND

%token<stringVal> T_FUNC_DELETE_MENU

%token<stringVal> T_FUNC_DELETE_TOOLBAR

%token<stringVal> T_FUNC_DEREF

%token<stringVal> T_FUNC_DIALOG_BOX

%token<stringVal> T_FUNC_DIRECTORY

%token<stringVal> T_FUNC_DOCUMENTS

%token<stringVal> T_FUNC_ECHO

%token<stringVal> T_FUNC_ELSE

%token<stringVal> T_FUNC_ELSE_IF

%token<stringVal> T_FUNC_ENABLE_COMMAND

%token<stringVal> T_FUNC_ENABLE_TOOL

%token<stringVal> T_FUNC_END_IF

%token<stringVal> T_FUNC_ERROR

%token<stringVal> T_FUNC_EVALUATE

%token<stringVal> T_FUNC_EXEC

%token<stringVal> T_FUNC_EXECUTE

%token<stringVal> T_FUNC_FCLOSE

%token<stringVal> T_FUNC_FILES

%token<stringVal> T_FUNC_FOPEN

%token<stringVal> T_FUNC_FOR

%token<stringVal> T_FUNC_FOR_CELL

%token<stringVal> T_FUNC_FORMULA_CONVERT

%token<stringVal> T_FUNC_FPOS

%token<stringVal> T_FUNC_FREAD

%token<stringVal> T_FUNC_FREADLN

%token<stringVal> T_FUNC_FSIZE

%token<stringVal> T_FUNC_FWRITE

%token<stringVal> T_FUNC_FWRITELN

%token<stringVal> T_FUNC_GET_BAR

%token<stringVal> T_FUNC_GET_CELL

%token<stringVal> T_FUNC_GET_CHART_ITEM

%token<stringVal> T_FUNC_GET_DEF

%token<stringVal> T_FUNC_GET_DOCUMENT

%token<stringVal> T_FUNC_GET_FORMULA

%token<stringVal> T_FUNC_GET_LINK_INFO

%token<stringVal> T_FUNC_GET_MOVIE

%token<stringVal> T_FUNC_GET_NAME

%token<stringVal> T_FUNC_GET_NOTE

%token<stringVal> T_FUNC_GET_OBJECT

%token<stringVal> T_FUNC_GET_TOOL

%token<stringVal> T_FUNC_GET_TOOLBAR

%token<stringVal> T_FUNC_GET_WINDOW

%token<stringVal> T_FUNC_GET_WORKBOOK

%token<stringVal> T_FUNC_GET_WORKSPACE

%token<stringVal> T_FUNC_GOTO

%token<stringVal> T_FUNC_GROUP

%token<stringVal> T_FUNC_HALT

%token<stringVal> T_FUNC_HELP

%token<stringVal> T_FUNC_INITIATE

%token<stringVal> T_FUNC_INPUT

%token<stringVal> T_FUNC_LAST_ERROR

%token<stringVal> T_FUNC_LINKS

%token<stringVal> T_FUNC_MOVIE_COMMAND

%token<stringVal> T_FUNC_NAMES

%token<stringVal> T_FUNC_NEXT

%token<stringVal> T_FUNC_NOTE

%token<stringVal> T_FUNC_OPEN_DIALOG

%token<stringVal> T_FUNC_OPTIONS_LISTS_GET

%token<stringVal> T_FUNC_PAUSE

%token<stringVal> T_FUNC_POKE

%token<stringVal> T_FUNC_PRESS_TOOL

%token<stringVal> T_FUNC_REFTEXT

%token<stringVal> T_FUNC_REGISTER

%token<stringVal> T_FUNC_REGISTER_ID

%token<stringVal> T_FUNC_RELREF

%token<stringVal> T_FUNC_RENAME_COMMAND

%token<stringVal> T_FUNC_REQUEST

%token<stringVal> T_FUNC_RESET_TOOLBAR

%token<stringVal> T_FUNC_RESTART

%token<stringVal> T_FUNC_RESULT

%token<stringVal> T_FUNC_RESUME

%token<stringVal> T_FUNC_RETURN

%token<stringVal> T_FUNC_SAVE_DIALOG

%token<stringVal> T_FUNC_SAVE_TOOLBAR

%token<stringVal> T_FUNC_SCENARIO_GET

%token<stringVal> T_FUNC_SELECTION

%token<stringVal> T_FUNC_SET_NAME

%token<stringVal> T_FUNC_SET_VALUE

%token<stringVal> T_FUNC_SHOW_BAR

%token<stringVal> T_FUNC_SPELLING_CHECK

%token<stringVal> T_FUNC_STEP

%token<stringVal> T_FUNC_TERMINATE

%token<stringVal> T_FUNC_TEXT_BOX

%token<stringVal> T_FUNC_TEXTREF

%token<stringVal> T_FUNC_UNREGISTER

%token<stringVal> T_FUNC_VIEW_GET

%token<stringVal> T_FUNC_VOLATILE

%token<stringVal> T_FUNC_WHILE

%token<stringVal> T_FUNC_WINDOW_TITLE

%token<stringVal> T_FUNC_WINDOWS

