version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    environment:
      - DOTNET_CLI_TELEMETRY_OPTOUT=1
      - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
    ports:
      - "5000:5000"
      - "5001:5001"
      - "8080:8080"
      - "3000:3000"

  # SQL Server for testing ODBC functionality
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=OpenLanguage123!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P OpenLanguage123! -Q 'SELECT 1'",
        ]
      interval: 30s
      timeout: 10s
      retries: 5

  # MySQL for testing alternative database connections
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=OpenLanguage123!
      - MYSQL_DATABASE=openlanguage_test
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  # PostgreSQL for comprehensive database testing
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=openlanguage_test
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=OpenLanguage123!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d openlanguage_test"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Redis for caching scenarios
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  sqlserver_data:
  mysql_data:
  postgres_data:
  redis_data:
