public A1AbsoluteColumnNode a1ColumnVal;
public A1AbsoluteRowNode a1RowVal;
public A1CellNode a1CellVal;
public RelativeCellRangeKeywordLeft relativeCellRangeKeywordLeftVal;
public RelativeCellRangeKeywordRight relativeCellRangeKeywordRightVal;
public RelativeCellRangeKeywordAbove relativeCellRangeKeywordAboveVal;
public RelativeCellRangeKeywordBelow relativeCellRangeKeywordBelowVal;
public RelativeCellRangeKeyword relativeCellRangeKeywordVal;
public TableReferenceNode tableReferenceVal;
public CellRangeNode<
    A1CellNode,
    A1CellNode,
    ulong,
    A1RowNode,
    ulong,
    A1ColumnNode,
    ulong,
    A1RowNode,
    ulong,
    A1ColumnNode
> cellRangeVal;
public CellReferenceNode cellReferenceNodeVal;
public CellReferenceNodeList cellReferenceNodeListVal;
public ulong ulongVal;

